/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ExternalObject<T> {
  readonly "": {
    readonly "": unique symbol;
    [K: symbol]: T;
  };
}
export interface TransformOutput {
  code: string;
  map?: string | undefined | null;
}
export interface TransformConfig {
  reactRuntime?: boolean | undefined | null;
  babelImport?: Array<BabelImportConfig> | undefined | null;
}
export interface BabelImportConfig {
  fromSource: string;
  replaceCss?: ReplaceCssConfig | undefined | null;
  replaceJs?: ReplaceSpecConfig | undefined | null;
}
export interface ReplaceSpecConfig {
  replaceExpr: string;
  ignoreEsComponent?: Array<string> | undefined | null;
  lower?: boolean | undefined | null;
}
export interface ReplaceCssConfig {
  ignoreStyleComponent?: Array<string> | undefined | null;
  replaceExpr: string;
  lower?: boolean | undefined | null;
}
export function transformBabelImport(
  code: string,
  config: TransformConfig,
  filename?: string | undefined | null,
  target?: string | undefined | null
): TransformOutput;
